HISTORY.rst, broker/hosts.py, setup.py
This updated version of awxkit is now compatible with pip 20+
I also removed the provider information from the host, as we likely won't need this for a while.
=> Update awkit dependency

HISTORY.rst, README.md, broker/commands.py, broker/hosts.py, broker/providers/ansible_tower.py, setup.py
This allows us to duplicate the arguments used to checkout a
system in our current inventory.
Also fixed some typos.
=> Adding duplicate command

broker/broker.py
I haven't taken the time to read through all of the existing code and
understand what it does, but as a general matter, it's a bad idea to
raise `Exception`, especially when doing so suppresses some other
exception. If `Exception` really is desired, I'd recommend:
raise Exception from err
=> Re-raise existing exception, not Exception

setup.py
People installing as instructed in the readme are getting left with dynaconf 2.2.3 installed, this prevents that, and just makes our requirements more explicit.
=> Specify dynaconf>3.0

broker/providers/ansible_tower.py, tests/data/ansible_tower/fake_workflows.json, tests/providers/test_ansible_tower.py
Handle the failure to find a workflow by name a little bit better, and log more information when executing workflows.
~~@JacobCallahan thoughts on the sys.exit call here? Would you rather a different pattern?~~
This used to result in an IndexError and traceback dump, captured and logged without the trace.
```
setup@localhost:~/repos/broker (handle-workflow-indexerror*>) % broker execute  --workflow does-not-exist
[INFO 200707 14:18:28] Using provider AnsibleTower for execution
[ERROR 200707 14:18:29] Workflow not found by name: does-not-exist
[INFO 200707 14:18:29] None
```
Add logging for the workflow template URL and the job URL, so the user can more easily identify and track their request.
```
setup@localhost:~/repos/broker (handle-workflow-indexerror*>) % broker execute  --workflow …
```
=> Wrap IndexError with log and exit condition

HISTORY.rst, README.md, broker/commands.py, broker/logger.py, setup.py
This change introduces the ability for broker to spin up another broker
subprocess and exit.
This new broker subprocess will also have a new log-level of "silent".
A "silent" log level has a level of INFO, but only logs to broker's log file.
=> [Alternate]Add background mode to Broker cli

broker/broker.py, broker/commands.py, broker/providers/ansible_tower.py, tests/providers/test_ansible_tower.py
This change adds the ability to override or supply your own
host classes via the VMBroker class.
VMBroker now looks for a kwarg called "host_classes" which should be
a dictionary mapping class name to the class object.
=> Bring your own host classes

broker/providers/ansible_tower.py
This is a potentially common encounter for more complex workflow
paths. This change skips all "transition" nodes.
=> Adjust for nodes without results

broker/providers/ansible_tower.py
* Inventory returns from `broker==0.1.0` are only returning a default of 25 inventory items
* For users that are allowed to deploy more than 25 VMs, this is a truncated list
```
(broker) ➜  broker git:(master) ✗ broker inventory --sync AnsibleTower:automation_user
[INFO 200825 11:21:23] Pulling remote inventory from AnsibleTower
[INFO 200825 11:21:25] No new hosts found
[INFO 200825 11:21:25] Pulling local inventory
[INFO 200825 11:21:25] 0: dhcp-2-252.box.com
[INFO 200825 11:21:25] 1: dhcp-3-90.box.com
[INFO 200825 11:21:25] 2: dhcp-3-119.box.com
[INFO 200825 11:21:25] 3: dhcp-3-137.box.com
[INFO 200825 11:21:25] 4: dhcp-3-65.box.com
[INFO 200825 11:21:25] 5: dhcp-3-5.box.com
[INFO 200825 11:21:25] 6: dhcp-2-17.box.com
[INFO 200825 11:21:25] 7: dhcp-2-188.box.com
[INFO 200825 11:21:25] …
```
=> Updating retrieved inventory to be practically larger than default 25

broker/settings.py, tests/test_broker.py
This change intends to make it more clear to users when their settings
need to be changed.
Additionally, some sane defaults can be added if missing.
=> Adding dynaconf validators to broker settings

README.md, broker/providers/ansible_tower.py, broker/settings.py, broker_settings.yaml.example
Support token authentication for AnsibleTower provider.
On the tower side, this requires an Application, which the tokens are registered under, and a global setting to allow token creation for OAuth users.
When using token, username and password settings are no longer necessary.
=> Use token authentication for Tower

broker/providers/ansible_tower.py
Adding expire time property for details command, this will require sync and needs cleaning of the inventory file. 
```
(env) [root@okhatavk broker]# broker inventory --details 
[INFO 200807 20:08:12] Pulling local inventory
[INFO 200807 20:08:12] 0: hostname_1.redhat.com, Details: _broker_args:
host_type: satellite
provider: RHEV
rhel_version: '7.7'
template: satellite-6.8.0-10.0
workflow: deploy-sat-lite
_broker_provider: AnsibleTower
expire_time: '2020-08-10 15:31:28'
hostname: hostname_1.redhat.com
name: okhatavk-satellite-6.8.0-10.0-1596793936
type: host
```
=> adding the property to see the vm host expire time

broker/logger.py
This change will now create the logs directory if it doesn't exist
at BROKER_DIRECTORY. This makes it so the BROKER_DIRECTORY doesn't
have to be broker's root directory.
=> Make broker more resilient to running outside its directory

broker/settings.py
- Nicks are not always used by everyone, for example, in my current jenkins implementation I don't have need for NICKS and broker fails, hence removing the validation.
=> Removing validator for NICKS as it shouldn't be mandatory

broker/providers/ansible_tower.py, tests/data/ansible_tower/fake_jobs.json
UI urls are a bit more user friendly
Use urllib.parse instead of mangling strings for URLs
Before, logged URLS had `http:/<host>/<path>`, which on console isn't parsed as a URI, and can't be directly clicked/linked. This was due to using `.replace()` to resolve any double slashes from the host ending with a slash and the path starting with a slash.
Output now looks like:
```
[INFO 200915 08:07:43] Using provider AnsibleTower to checkout
[INFO 200915 08:07:43] Using username and password authentication
[INFO 200915 08:07:45] Waiting for job: 
API: https://<host>/api/v2/workflow_jobs/1363/
UI: https://<host>/#/workflows/1363
```
=> Update tower logging to provide UI URLs

broker_settings.yaml.example
If a user copies the example and only sets username/password, like they're likely to with envvars, token will override their envvar use
Keep the default behavior on copying broker_settings.yaml.example as simple as possible, changing as few values as possible for a clean configuration
=> Make the settings example have token commented out

.travis.yml, HISTORY.rst, README.md, broker/commands.py, setup.cfg, setup.py
This change now allows a cli user to gain more information about
what they can do with broker and its providers.
The new providers command is dynamically generated from information,
about providers and their actions, stored in broker.py
fixes #41
=> nick-help command now changed to providers

broker/providers/test_provider.py, tests/test_broker.py
Pickling of an attribute in test_provider led to deadlock in the test. The whole module was used which is not picklable. The pickling is required for the `Queue.put`
Fixes #44
The PR #53 makes the error reporting much better.
=> Fix pickling, enable test_mp_checkout

broker/commands.py
This provides some useful information about the files broker cares about
fixes #22
my output
```
Version: 0.1.3
Broker Directory: /home/jake/Programming/broker
Settings File: /home/jake/Programming/broker/broker_settings.yaml
Inventory File: /home/jake/Programming/broker/inventory.yaml
Log File: /home/jake/Programming/broker/logs/broker.log
```
=> Added --version to main broker command

.travis.yml, broker/broker.py, broker/providers/test_provider.py, setup.py, tests/test_broker.py
This makes the behavior of broker in case of exception rised in the child much better (without this PR, there is a deadlock and possible no output on the terminal about the exception. With this PR the exception is propagated to the parent process.
There were issues that I think were arising from using a decorator that replaced the decorated method with some nested method (the `wraps` function is commonly used in that case). It seems to me such method cannot be pickled but that seemed necessary for sending it to the `concurrent.futures`
=> Use concurrent.futures to fix multiprocessing issues

broker/commands.py, broker/providers/ansible_tower.py
It currently reads from a relative setup.py file
New change doesn't rely on setup.py
Also small changes to providers generated help, removing duplicated limit and filter entires
Removed duplicates from --list-templates and reverse sorted ("higher" versions first)
=> Fix broker version command

broker/commands.py, broker/providers/__init__.py, broker/providers/test_provider.py
It seems to me the TestProvider it is not just filtered from listing the providers:
```
$ broker providers 
Usage: broker providers [OPTIONS] COMMAND [ARGS]...
Get information about a provider and its actions
Options:
--help  Show this message and exit.
Commands:
AnsibleTower  Get information about a provider's actions
$ broker providers AnsibleTower
[INFO 201013 13:41:13] Querying provider AnsibleTower
[INFO 201013 13:41:13] Using username and password authentication
```
As AnsibleTower can be used, but TestProvider cannot:
```
$ broker providers TestProvider
Usage: broker providers [OPTIONS] COMMAND [ARGS]...
Try 'broker providers --help' for help.
Error: No such command 'TestProvider'.
```
Therefore I conclude the TestProvider cannot be used from CLI without manually changing the code …
=> Make TestProvider hidden instead of "not-loading it".

broker/providers/ansible_tower.py
Its unclear during checkouts with `--count >1` which of the workflows has failed.
```
broker --log-level debug checkout --workflow deploy-workflow --count 3
[...]
[I 210205 21:14:54 ansible_tower:255] Waiting for job: 
API: https://<host>/api/v2/workflow_jobs/236262/
UI: https://<host>/#/workflows/236262
[I 210205 21:14:54 ansible_tower:255] Waiting for job: 
API: https://<host>/api/v2/workflow_jobs/236263/
UI: https://<host>/#/workflows/236263
[I 210205 21:14:54 ansible_tower:255] Waiting for job: 
API: https://<host>/api/v2/workflow_jobs/236264/
UI: https://<host>/#/workflows/236264
[E 210205 21:18:06 ansible_tower:260] Workflow Status: failed
Explanation: No error handling paths found, marking workflow as failed
[D 210205 21:18:06 broker:91] None
[D 210205 21:18:06 broker:112] …
```
=> Log the workflow/job-template link on failure

broker/broker.py, broker/commands.py, broker/providers/ansible_tower.py
**Description:**
With the incoming requirement to have broker accept and pass along inventory information, it would be nice to let users be able to figure out what queries are available.
Desired usage:
Get a list of inventories your account has access to.
**broker providers AnsibleTower --inventories**
Optional usage:
Get some relevant information about an inventory.
**broker providers AnsibleTower --inventory test-inventory**
Test Results:
=> List AnsibleTower Inventories

broker/helpers.py
If the nicks list in `broker_settings.yaml` is empty, `nick_names` gets set to `None` resulting in a `TypeError`.
=> Handle empty nicks list

broker/providers/__init__.py
This makes it so you don't have to put extraneous config keys when there is only one provider instance available.
Without `default: true` in your settings, you'll see a pretty obtuse exception that doesn't really indicate what's wrong:
```
File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/broker/broker.py", line 222, in sync_inventory
prov_inventory = PROVIDERS[provider](**instance).get_inventory(additional_arg)
File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/broker/providers/ansible_tower.py", line 45, in __init__
self._validate_settings(instance_name)
File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/broker/providers/__init__.py", line 36, in _validate_settings
fresh_settings.update(instance.values()[0]) …
```
=> Made a singular provider instance the default automatically

HISTORY.md, README.md, broker/commands.py, broker/helpers.py, setup.py, tests/data/args_file.json, tests/data/args_file.yaml, tests/data/broker_args.json, tests/data/broker_args.yaml, tests/test_helpers.py
This change allows users to use files to store arguments.
Broker will attempt to resolve these files at runtime and pass them
along to the provider.
Since the values override the runtime broker_args, the resolved values
are stored in the inventory file so modified/destroyed files won't
result in improper behavior during a duplicate action.
fixes #87
=> Added the ability to pass in complex data structures via files

.travis.yml, HISTORY.md, broker/__init__.py, broker/broker.py, broker/commands.py, broker/exceptions.py, broker/helpers.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/settings.py, broker_settings.yaml.example, setup.py, tests/cli_scenarios/test_satlab.py, tests/data/cli_scenarios/satlab/checkout_latest_rhel.yaml, tests/data/cli_scenarios/satlab/checkout_latest_sat.yaml, tests/data/cli_scenarios/satlab/checkout_rhel78.yaml, tests/data/cli_scenarios/satlab/checkout_sat_69.yaml, tests/data/cli_scenarios/satlab/execute_templates_list.yaml, tests/data/cli_scenarios/satlab/execute_test_workflow.yaml, tests/providers/test_ansible_tower.py, tests/test_settings.py
Broker can now accept ansible tower inventories both via cli and config.
We now have a new exception handling system as well as a way to
gracefully handle kyboardinterrupts.
Providers can now specify checkout and execute cli arguments in their
class definition.
Minor refactor and improvements.
=> Add the ability for broker to process ansible tower inventories

HISTORY.md, broker/providers/ansible_tower.py, setup.py
This will not send the inventory payload and let tower decide the
inventory.
=> Allow users to not specify an inventory for AnsibleTower

broker/broker.py, broker/exceptions.py
Set default values instead of required, this allows the exceptions
to be pickled by multiprocessing.
Also handled a case where no host would be returned.
fixes #104
=> Make custom exceptions work with multiprocessing

broker/broker.py
Added an error message: "Could not determine an appropriate provider" when the user does not specify options to certain commands. Ex: `broker execute` or `broker checkout` with no workflow or nick.
=> Adding error message when no flags are specified

broker/broker.py, broker/hosts.py, broker/session.py
If connect wasn't called, session can be referenced when it was None. Callers should be able to create a host instance and use its `execute` method without being forced to connect first. Broker should be responsible for handling that session connection.
This will replace session whenever `connect` is called.
Since connect is handled automatically along with the session property, there is no longer a need to track connected state through pickling, so `__setstate__` has been removed.
Example, where `host` was created with `VMBroker.from_inventory()`:
```
In [7]: host.execute('hostname')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-0a254b67faf4> in <module>
----> 1 …
```
=> Turn host.session into a property

HISTORY.md, broker/providers/ansible_tower.py, broker/settings.py, setup.py
AnsibleTower will only display workflow and job templates a user had permission to start
fixes #110
=> Restrict AT workflow and job tempate output lists

broker/broker.py, broker/commands.py
Sequential argument added for those that want it, but the default will be concurrent checkins.
Can't use mp_decorator due to its pattern of duplicating the same function kwargs, just using ProcessPoolExecutor directly
It's fairly subtle in the examples below because checkins ran without delay, but its clear in the sequential one it waited to start the task until the first checkin was complete.
Default concurrent checkin of multiple instances:
```
setup@localhost:~/repos/robottelo (master$%>) % broker checkin 0 1             
[INFO 210624 08:03:37] Using token authentication
[INFO 210624 08:03:38] Using token authentication
[INFO 210624 08:03:39] Checking in <host0>
[INFO 210624 08:03:39] Checking in <host1>
[INFO 210624 08:03:39] Using token authentication
[INFO 210624 08:03:39] Using …
```
=> Add parallel checkin behavior as default

broker/broker.py
Move the inventory update out of the MP process for checkin, attempt to mitigate pickle encoding characters breaking yaml parsing.
Observed during single host checkin with ContentHost hosts from robottelo. 
@JacobCallahan is also looking at a pattern to make host instances pickle-safe.  Throwing this up for visibility.
```
Traceback (most recent call last):
File "/usr/lib64/python3.8/concurrent/futures/process.py", line 239, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/broker/broker.py", line 183, in _checkin
helpers.update_inventory(remove=host.hostname)
File "/opt/app-root/lib64/python3.8/site-packages/broker/helpers.py", line 224, in update_inventory
inv_data = load_inventory()
File …
```
=> Move inventory update to after mp checkins complete

.github/workflows/python-publish.yml, .github/workflows/update_broker_image.yml, HISTORY.md
Added to try and make it compatible with nektos/act, but breaks
container build in GHA as-is.
Updating history because it has to be updated for workflows to trigger
=> Remove context from update broker image workflow

HISTORY.md, broker/broker.py, broker/hosts.py, tests/test_broker.py
I found that checkin was getting called against an instance that had no
hosts, triggering a ValueError because 0 was getting passed for
max_workers to ProcessPoolExecutor
Changed the context manager to not capture and try to checkin when no
hosts were created.
Checked that hosts isn't empty in VMBroker.checkin
Added unit test that reproduced the error
=> Check for empty hosts in VMBroker.checkin

.github/workflows/python-publish.yml, setup.cfg, setup.py
This commit implies we will begin to use git tags to control versioning in broker, instead of a static version number in setup.py.
We'll still manually update HISTORY.md with contextual information about tagged versions.
=> Move to setup.cfg, use setuptools-scm for versioning

.github/workflows/python-publish.yml
Might _have_ to use an `if` statement in the job body, but I'd like to keep things simpler if possible.
=> Limit python-publish to tags only

HISTORY.md, broker/commands.py, broker/providers/ansible_tower.py
This change allows broker to also handle jobs that error out instead
of simply failing. It also provides a generic error message if none
could be found.
=> Better job error handling for AnsibleTower

.github/workflows/codeql-analysis.yml, .gitignore, HISTORY.md, broker/broker.py, broker/commands.py, broker/helpers.py
This will pass along an exception object from the mp checkouts and
then check/raise them later. In a CLI environment, this will also give
us the correct exit code
=> Made CLI checkouts properly raise exceptions

HISTORY.md, broker/helpers.py, tests/test_helpers.py
This should help us mitigate the occasional race conditions when
multiple instances of broker are attempting to update a single local
inventory file.
=> Added a locking mechanism to actions that modify files

HISTORY.md, broker/hosts.py, broker/providers/ansible_tower.py, broker/session.py, broker/settings.py
This timeout is both available as a setting as well as when creating a Session instance.
=> Adding a connection timeout option

broker/session.py
We're hitting an issue, where we obtain a false exit status from a `.run()` method (currently only on a rhel9 host, which is interesting - but the VM is created using different template, so the HW profile might be different [slower VM]):
```
(Pdb++) for i in range(100): foo = host2.session.run('rpm -qa |grep katello-ca-consumer'); print(f'{foo.status}, {foo.stdout}, {foo.stderr}')
0, , (0, b'')
1, , (0, b'')
1, , (0, b'')
1, , (0, b'')
1, , (0, b'')
0, , (0, b'')
1, , (0, b'')
...
```
After some investigation, i found [this example](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/example_echo.py#L36-L44) in the upstream lib, that gives me the correct exit_status every time.
Comparing to what we have in our code base, it looks like we try to read the channel before actually …
=> fix intermittent false exit status reads from commands

.github/workflows/codeql-analysis.yml, .gitignore, README.md, broker/__init__.py, broker/binds/containers.py, broker/broker.py, broker/commands.py, broker/helpers.py, broker/hosts.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/providers/container.py, broker/session.py, broker_settings.yaml.example, setup.cfg, tests/data/cli_scenarios/containers/checkout_ch-d_ubi8.yaml, tests/data/cli_scenarios/containers/execute_ch-d_ubi8.yaml, tests/data/cli_scenarios/satlab/checkout_rhel78.yaml, tests/data/container/fake_containers.json, tests/data/container/fake_images.json, tests/functional/README.md, tests/functional/test_containers.py, tests/functional/test_satlab.py, tests/providers/test_ansible_tower.py, tests/providers/test_container.py, tests/test_broker.py
This pr introduces the container provider.
The first supported bind is Docker, though a Podman bind is in progress.
A number of other supporting concepts have also been introduced, most
notably are "binds". These are small abstraction layers around an
external API that ease the integration into Broker.
=> Introducing the Container provider

broker/settings.py, tests/test_settings.py
There is an issue with dynaconf - still being discussed and written as
an RFE upstream - where consumers of broker are using `.env` files and
configuring their dynaconf instances to read this file.
This causes the broker dynaconf instance to have a partial config based
on the `.env` file from the broker consumer, resulting in a broken
broker dynaconf instance.
In the particular case, robottelo is using broker and is storing
dynaconf vault config within the .env file. The vault config is not
complete, and within broker the settings instance throws exceptions
trying to read from vault.
I would consider this change a workaround for the behavior, not a real
resolution.
It should not interfere with the direct use of broker, or the use of
broker by consumers that are not using vault and not …
=> Load env file for dynaconf

broker/settings.py, tests/test_settings.py
This change is needed due to dynaconf #751. This happens when broker is
being used in a project that is using dynaconf's vault integration.
Also reverted the previous try for good measure
=> Add workaround to disable dynaconf vault loading

broker/binds/containers.py, broker/helpers.py, broker/hosts.py, broker/providers/ansible_tower.py, broker/providers/container.py, broker/session.py, tests/data/cli_scenarios/containers/checkout_ch-d_ubi8.yaml, tests/data/cli_scenarios/containers/execute_ch-d_ubi8.yaml, tests/functional/test_containers.py
This change adds the ability to use "sftp" actions against containers.
This is done by (un)packing files in tar archives, which can be added/copied from running containers.
There isn't a current implementation to emulate an interactive shell, but that is likel possible with attach_socket.
I also made some unrelated optimizations to existing code.
=> Simulate SSH Session functionality with Container-based Hosts

broker/broker.py
This change is largely for users attempting to check in a lot of hosts at once. When too many are being checked in, we can get in a situation where the user's OS' open files limit it reached. At that point, an exception is raised and no more hosts will be checked in.
By the new default, the checkin process will use as many workers as there are CPUs on the machine.
=> Change the mp checkin max workers to default

broker/helpers.py, broker/providers/container.py, tests/test_helpers.py
This change attempts to get the request object when we're running in a pytest fixture We then return the test location information gathered from the request object
=> Get more specific with the origin information when in a pytest context

.github/workflows/codeql-analysis.yml, broker/helpers.py, broker/hosts.py, broker/providers/__init__.py, broker/providers/container.py, tests/data/cli_scenarios/satlab/checkout_rhel78.yaml, tests/functional/test_containers.py
An issue was identified where the _cont_inst property was being stripped from the modified Host class during MP checkouts.
The solution I opted for was to recreate the missing container instance post-pickle. This removed the entire need for the _cont_inst property.
=> Solve an issue with MP container checkouts

README.md, broker/commands.py, broker/helpers.py, broker/providers/container.py
addresses:
https://github.com/SatelliteQE/broker/issues/174
These commits add support for additional env vars. the following approaches work:
nick:
```
my_nick:
container_host: "ubi8:rplevka"
environment:
ARG1: "val1"
ARG2: "val2"
```
cli:
```
broker checkout --nick my_nick --environment "ARG1=val1,ARG2=val2"
```
Also, the processing of the `args_file` was refactored to combine parsed args with eventual cli args (cli args taking precedence)
=> support passing additional env vars to host

broker/session.py, tests/functional/test_containers.py, tests/functional/test_satlab.py
This change adds some additional logic to not only handle when parent directories don't exist, but also constructs the destination path when only a directory is given
Fixes #169
Both affected functional tests pass
=> Better handle situations where the parent directory doesn't exist during sftp

broker/providers/ansible_tower.py
Our AAP instance is moving away from username/password auth. Users will soon be required to use a token.
=> Add deprecation message for Ansible Tower provider

broker/providers/__init__.py, tests/functional/test_containers.py, tests/functional/test_satlab.py
This change works around an issue we've seen with Dynaconf loading fresh settings in a threaded environment.
Additionally, bumped the concurrency of functional tests
Fixes #179
=> Improve thread-safety with provider classes

broker/broker.py, broker/helpers.py, broker/providers/ansible_tower.py, broker/settings.py, setup.cfg, tests/functional/test_satlab.py, tests/providers/test_container.py, tests/test_helpers.py
Fixes #172
Fixes #146
Fixes typos and stylecheck
Updates setup.cfg
(no squash please)
=> Fix handling of ProviderException

broker/binds/containers.py, broker/broker.py, broker/commands.py, broker/helpers.py, broker/logger.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/providers/container.py, broker/settings.py, broker_settings.yaml.example
This PR is a rebase of #126 onto the current `master`.
* Dedup update_provider_action.
* Log the click commands
* Monkeypatch the awxkit to be more verbose
* Add log messages
* defined `setup_logzero` function to keep compatibility with logging setup in robottelo
* changed the way logging is configured - potential breaking change `settings.debug` option will not exist anymore. Users will have to adopt the new config format.
* added colors to the TRACE level messages
* redacted sensitive attributes from broker logs
* fixed a typo :stuck_out_tongue: 
* TODO
=> REBASED: Make Broker able to log more verbosely

broker/binds/containers.py, broker/broker.py, broker/commands.py, broker/logger.py, broker/providers/ansible_tower.py, broker/settings.py
* formatted logging related code using black
* removed deprecated logzero.setup_default_logger
* broken down into logzero.formatter, logzero.loglevel and logzero.logfile
* fixed broken logging in ipython console with %autoreload 2 turned on
* _old_factory is None by default and is set to `broker_record_factory` only if _old_factory was not set to `broker_record_factory` yet.
=> Logging improvements & fixes

broker/providers/ansible_tower.py
Resolves https://github.com/SatelliteQE/broker/issues/191
Output sample:
```
broker providers AnsibleTower --workflow deploy-base-rhel
[INFO 230220 09:36:17] Querying provider AnsibleTower
[INFO 230220 09:36:17] Using token authentication
[INFO 230220 09:36:18] 
Description:
Workflow to deploy Base RHEL with only deploy_version_choice required. Defaults to RHEL 7.9 deploy with no options.
Accepted additional nick fields:
deploy_scenario: baserhel
deploy_rhel_version: ''
host_type: host
tower_inventory: <inventory_name_here>
```
=> Adding description and default inventory to workflow and jt output

broker/commands.py, broker/providers/ansible_tower.py
This change allows users to pass along additional arguments to provider help commands. Providers can then choose to use these arguments as they see fit.
One new possible example is to specify a tower_inventory when listing the available templates for AnsibleTower.
I also added a couple of new logging statements to make it clear what tower inventory is being used by Broker and when.
=> Allow for additional arguments to be passed to provider help commands

broker/broker.py
This PR adds a new optional parameter to the Broker class, `skip_checkin,` which can be set to `True` when instantiating the class to skip the check-in step when exiting the context.
If `skip_checkin` is not set or is set to False, the `__exit__` method will proceed with the normal check-in process, which includes attempting to perform a teardown on each host in the `_hosts` list and calling the `checkin` method to perform the final check-in step.
This change is useful when the `Broker` instance is being used in a context where a check-in is not necessary or desired, such as when performing read-only operations on remote servers.
=> skip the broker check-in part of the context manager

broker/providers/ansible_tower.py
fixes #199
In case when `VM inventory != default inventory`:
Broker tries to delete the `inventory` attribute (cached_property)  even though it is not evaluated yet. That results in `'AnsibleTower' object has no attribute 'inventory'`
I propose to check whether it was evaluated using `__dict__` first and then safely delete it.
=> Delete property only if it exists

broker/broker.py, broker/helpers.py, broker/hosts.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker_settings.yaml.example, tests/test_settings.py
We're currently seeing an issue with data loss in OSP hosts from AAP. This commit introduces a couple of ways around this.
1. Try to recover the fqdn from the openstack metadata in host variables, if present.
2. Inventory sync are now non-destructive for data within a host.
Second commit adds a few fixes
Third commit introduces some changes to the way instances are evaluated. It makes instances optional and allows for each instance to specify whether or not it can override envars set at the Provider level.
Fixes #195
Fixes #198
Fixes #184
=> Make inventory syncs more resilient to data loss

.github/workflows/codeql-analysis.yml, README.md, broker/helpers.py, broker/settings.py, broker_settings.yaml.example
This change creates a new standard for where Broker files are located. By default, Broker will be based in ~/.broker/ but will still listen for the BROKER_DIRECTORY environment variable.
As a result, Broker will no longer honor any alternative locations for its inventory file.
Fixes #190
=> [0.3.0] Make Broker more opinionated about where its files are located

broker/broker.py, broker/commands.py, broker/helpers.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/providers/container.py, broker/providers/test_provider.py
This new version is more in-line with a plugin-based approach.
A Provider author can now create a new Provider class and register it
without having to touch any other files but their own.
To do this, we now have automatic registration of any class that inherits
from the base Provider class. Additionally, registering actions is done via
a new decorator.
Also
Remove PickleSafe base class
Broker has moved from multiprocessing to multithreading for concurrency.
Because of this, we no longer have to worry about pickling objects.
=> [0.3.0] Refactor Provider registration system

broker/logger.py
Currently, broker initializes with the logger called `logzero_default`.
This commit makes `setup_logzero` to accept custom name or uses `broker` by default.
Same way, it adds an option to pass custom formatter. This is useful while used by robottelo, so they can log the messages using the same format.
Robottelo PR that uses that leverages this feature:
https://github.com/SatelliteQE/robottelo/pull/11130
=> add optional formatter and name params to setup_logger

.github/workflows/codeql-analysis.yml, broker/commands.py, broker/settings.py, setup.py
When the settings file is missing from the user's Broker directory,
Broker will prompt them to download the file from GitHub and open an editor.
=> [0.3.0] Add the ability for Broker to download a missing settings file

broker_settings.yaml.example
This simplifies and clarifies the AnsibleTower provider's example settings.
I think more can be done here in the future around removing the test settings, but that's beyond this update.
=> Simplify broker_settings.yaml.example

broker/hosts.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/providers/container.py
This change fixes an issue we're seeing where host entries, missing a hostname and ip, are being reconstructed for checkin. While that shouldn't be an issue during checkin, it would be if used for other purposes.
With that in mind, this adds a check to see if the host is being reconstructed. If so, then it will just debug log instead of raising an error.
Add in some new workarounds and log statements
We're seeing some strange behavior in CI. These are attempts to solve them
and/or get more information about what's going on.
=> Add contextual awareness to host creation

broker/hosts.py, broker/session.py, tests/functional/test_containers.py, tests/functional/test_satlab.py
This is a pretty common request and should be useful in a number of scenarios. Usage is pretty simple:
```python
with my_host.session.tail_file("/var/log/messages") as res:
print(res.stdout)
```
=> Add a tail_file context manager to the Host class

broker/hosts.py, broker/session.py, broker/settings.py
What?
Let the user give a timeout for socket.connect(). Default is still 60.
Why? 
In cloud VMs, we get Connection Refused as the machine is not ready to take ssh connection just yet. Increasing the timeouts(reties) solves the issue.
Usage:
```
with Session(username="ec2-user",  hostname=hostname,  key_filename=private_key_path, socket_connect_timeout=500) as host:
assert "hostname" in host.run("rpm -q hostname").stdout
```
=> Custom socket connect timeout in Session()

broker/hosts.py, broker/providers/test_provider.py, tests/test_broker.py
Let's have the following host
```python
class IPAHost(Host):
def __init__(self, sat_obj, **kwargs):
self.satellite = sat_obj
kwargs['hostname'] = kwargs.get('hostname', settings.ipa.hostname)
kwargs['from_dict'] = True
kwargs.update(
{
'base_dn': settings.ipa.basedn,
'disabled_user_ipa': settings.ipa.disabled_ipa_user,
}
)
super().__init__(**kwargs)
```
Then the following code snippet
```python
sat = Host('foo.bar')
ipahost = IPAHost(sat)
ipahost.hostname
```
will fail with `AttributeError: 'IPAHost' object has no attribute 'hostname'`
The `Host` `__init__` stores the `hostname` and the `name` in args, not in `kwargs`. So we need to set `name` and `hostname`  directly regardless of what `from_dict` is set to.
Ref: SatelliteQE/robottelo#11445
This is most likely the first host that is …
=> Turn Host kwargs into object's attributes every time

broker/broker.py, tests/functional/test_containers.py, tests/test_broker.py
This change introduces a way to carry out multiple kinds of checkouts at the same time when using Broker as a library.
from the docstring:
```
Given a mapping of names to Broker argument dictionaries:
create multiple Broker instances, check them out in parallel, yield, then checkin.
Example:
with Broker.multi_mode(
rhel7={
"host_class": ContentHost,
"workflow": "deploy_base_rhel",
"deploy_rhel_version": "7",
},
rhel8={
"host_class": ContentHost,
"workflow": "deploy_base_rhel",
"deploy_rhel_version": "8",
}
) as host_dict:
pass
All are checked out at the same time. The user is presented with the hosts in
a dictionary by argument name e.g. host_dict["rhel7"] is a ContentHost object
```
=> Add Broker.multi_manager

broker/providers/ansible_tower.py, tests/data/ansible_tower/fake_workflows.json, tests/providers/test_ansible_tower.py
This change ensures that we don't send multiple "source_vm" parameters into the AnsibleTower release method.
=> Quick fix for AnsibleTower provider

README.md, broker/binds/beaker.py, broker/broker.py, broker/commands.py, broker/exceptions.py, broker/helpers.py, broker/hosts.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/providers/beaker.py, broker/providers/container.py, broker/providers/test_provider.py, broker_settings.yaml.example, setup.cfg, tests/data/beaker/job_result.json, tests/data/beaker/test_job.xml, tests/data/cli_scenarios/beaker/checkout_test_job-2.yaml, tests/data/cli_scenarios/beaker/checkout_test_job.yaml, tests/functional/README.md, tests/functional/test_rh_beaker.py, tests/providers/test_beaker.py, tests/test_broker.py, tests/test_helpers.py
This change adds a very basic Beaker provider and its bind. For now, this relies on the beaker-client cli and config through that. Currently the only supported checkout/execute method is via job xml.
=> Add initial support for a Beaker provider.

broker/logger.py, broker/session.py, tests/functional/test_satlab.py
This change allows a user to supply a different destination path for remote_copy.
Fixes #165
=> Allow remote_copy to copy to a different path

catalog-info.yaml
Modified the catalog-info.yaml file to add namespace, owner and lifecycle
=> Updated catalog-info.yaml file for Backstage

broker/helpers.py, setup.cfg, tests/test_helpers.py
This change removes some unnecessary parts of the class to cut out wasted time and hopefuly reduce the chance of hitting a race condition.
=> Simplify FileLock class implementation

tests/test_broker.py
This simply adds the temp_inventory fixture to the file for this test. There are a few tests in different locations that also use this fixture so in the future, these could likely be consolidated.
=> Fixing test that assumed local inventory was blank

.github/workflows/python-publish.yml
The new process has been simplified now that we've moved away from using setup.py and rely on pyproject.toml
This uses the newer build system recommended by PyPA
=> Update build action

broker/providers/ansible_tower.py
We're currently seeing an issue with awx where it's returning multiple possible matches based on substring matches. This is creating false ambiguous matches. This change adds a manual filter to the search results to ensure that we only return exact matches, or at least do a bit better.
=> Add manual filtering of potential inventory searches

broker/commands.py, pyproject.toml
Now that packaging is no longer part of the standard library, we need to add it to the list of dependencies. This solves the issue seen when trying to run `broker --help`.
=> Add packaging to list of dependencies

broker/session.py
This PR adds authentication using ssh-agent, see https://github.com/SatelliteQE/broker/issues/246
Also exception handling for authentication is unified.
=> Authentication using ssh-agent

.pre-commit-config.yaml, broker/broker.py, broker/providers/container.py, pyproject.toml
Ruff now offers code formatting that is largely black-compatible, with some deviations [1]. Since we are already using Ruff for code linting in the project, we can also rely on it to handle code formatting. This will not only decrease the number of dependencies, but also be faster and (arguably) better formatted.
[1] - https://docs.astral.sh/ruff/formatter/black/
=> Swap Broker formatting from black to ruff

catalog-info.yaml, catalog/system/broker.yaml
Added system and location information so the Broker tool can be seen correctly under quality-community domain
=> Added system and location information for catalog-info.yaml

.github/workflows/python-publish.yml, .github/workflows/update_broker_image.yml, .gitignore, Dockerfile, broker/settings.py
The quay publish job is having trouble installing broker in the container. I simplified the Dockerfile a bit and things are building correctly locally.
I also improved the interactive logic with the settings file download, this was initially reproduced by running the container for `--version` while not passing interactive flags to docker.
=> Attempt to fix broker quay image build/push

broker_settings.yaml.example
This PR just changes a variable name in the example `nicks` section of `broker_settings.yaml.example`.  No code change.
=> Fix variable name in example broker_settings

broker/providers/ansible_tower.py
This isn't really used anymore. If this is brought back in the future, it would likely best be introduced as a new fact instead of separate attribute on the host.
=> Remove expire date information from AnsibleTower

broker/providers/ansible_tower.py
Get **_broker_args** from host's **ansible_facts**, if present, instead of from the job / workflow job attributes.
=> Use host facts when syncing inventory from AAP

broker/hosts.py, broker/session.py, broker/settings.py, broker_settings.yaml.example
This change is mostly focused around the addition of IPv6 connection functionality to Broker's Host Sessions.
Included are options for an ipv6 connection preference with an opt-out ipv6 connection fallback.
These have also been added to the settings file.
=> Add IPv6 support

README.md, broker/session.py, pyproject.toml
The intent of this change is to get us back to publishing Broker to PyPi. In order to do this, I split the ssh2-python github dependency from the main dependencies and into the the extras. As part of this, this also allows users to choose their ssh2-python backend (3.12 fork or 3.11 and earlier main package).
=> Split ssh2-python into an extra dependency

broker/commands.py
This is an under-utilized sub-command, so it will be removed in the next Y release pending any major objections.
=> Add deprecation message for duplicate

broker/hosts.py, broker/providers/ansible_tower.py, tests/data/ansible_tower/fake_workflows.json
- In `_merge_artifacts`, update documented values for `strategy` param and add some code comments documenting behavior.
- Rename `job_attrs` to `artifacts` in `construct_host`, to reflect the source of the data.
- In `execute`, send a new variable, `_broker_extra_vars`, containing a copy of any key/value pairs sent as `extra_vars` that aren't defined on the workflow. This will be used to track any custom variables defined by broker.
- Store and display host-specific inventory details (ip address, nics, etc.) at the top-level, outside of `_broker_args`:
```
[INFO 240208 09:55:00] 1: host.example.com:
_broker_args:
_broker_origin: broker_cli:tpapaioa
[...]
tpapaioa_arg1: val1
workflow: deploy-rhel
_broker_provider: AnsibleTower
_broker_provider_instance: aap
hostname: host.example.com
ip: …
```
=> AnsibleTower inventory updates/fixes

broker/providers/ansible_tower.py
Fix Ansible inventory sync to call default job lookup method only when host facts lookup method fails.
=> Fix Ansible inventory sync

pyproject.toml
Since making it an extra didn't help with PyPi, I'm moving this back up until we have a better option. This will simplify installs from github.
=> Moving ssh2-python fork dependency back to main list

broker/session.py
In our use case we create a backup of a config file, modify the config file (adding characters), perform testing and restore the original config from backup. We use sftp to read and write the backup. However the restore (sftp_write) ends with damaged config file. Damaged file consists of original content and few characters remained from modified file.
Adding flag LIBSSH2_FXF_TRUNC should solve the problem by truncating existing files.
see: https://libssh2.org/libssh2_sftp_open_ex.html
=> truncate existing files on sftp write

.github/workflows/codeql-analysis.yml, .github/workflows/python-publish.yml, .gitmodules, Dockerfile, pyproject.toml
In another attempt to circumvent the restrictions from PyPI, I am adding a submodule for my fork of ssh2-python and adding that as a local build requirement.
=> Vendor ssh2-python as a submodule

.github/workflows/codeql-analysis.yml, .github/workflows/python-publish.yml, .gitmodules, Dockerfile, broker/session.py, pyproject.toml
This change reverts those introduced to add submodule-based inclusion of the ssh2-python dependency.
Additionally, I added a attempt to reconnect to dead sessions (when servers reboot).
=> Revert ssh2-python submodule

pyproject.toml
Ssh2-python dependency installation during broker installation is failing :
```
WARNING: Generating metadata for package ssh2-python produced metadata for project name ssh2-python312. Fix your #egg=ssh2-python fragments.
11:04:43  ERROR: Could not find a version that satisfies the requirement ssh2-python (unavailable) (from broker) (from versions: 0.1b1, 0.2.0, 0.2.1, 0.3.0, 0.3.1.post2, 0.3.1.post3, 0.4.0, 0.5.0, 0.5.0.post1, 0.5.1, 0.5.2, 0.5.3rc1, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.7.0.post2, 0.7.0.post3, 0.7.0.post4, 0.7.0.post5, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.11.0.post1, 0.13.0.post2, 0.14.0, 0.15.0, 0.15.0.post2, 0.15.0.post4, 0.15.0.post7, 0.15.0.post8, 0.15.0.post9, 0.16.0, 0.17.0, 0.18.0.post1, 0.19.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 1.0.0rc2, 1.0.0)
11:04:43 …
```
=> Fix module name for ssh2-python312

README.md, pyproject.toml
This change moves away from the github fork-based dependency to the newly published ssh2-python312 on PyPI.
=> Swap ssh2-python dependency to ssh2-python312

broker/providers/ansible_tower.py
It seems that we don't always get a json object back from the api for the extra_vars available in a job. In these cases, we'll try a custom parser.
=> Adjust extra_vars handling in non-json cases

.github/workflows/python-publish.yml, pyproject.toml
A previous update changed the installation deps for python publish. This resulted in missing build dependencies.
Additionally, some old ruff rules have been removed.
=> Updates to publish and pyproject.toml

tests/data/cli_scenarios/satlab/checkout_sat_613.yaml
The functional test which deploy Satellite 6.11 failed in internal testing. Updating it to use Satellite 6.13, as 6.11 is now EOL.
=> Update functional test to deploy newer satellite version.

README.md, broker/commands.py, pyproject.toml
This was previously deprecated and we received no feedback to keep it in.
I also updated the podman python binding to the newly active name.
=> Remove the duplicate subcommand

broker/commands.py
Removes the deprecated usage of the `pkg_resources` module.
https://github.com/SatelliteQE/broker/issues/283
This change affects only the internals of the `broker --version` command. The command output is unaffected. Example output with this change:
```
$ broker --version
Version: 0.4.10.dev2+g6db4e5b
Broker Directory: /home/tpapaioa/.broker
Settings File: /home/tpapaioa/.broker/broker_settings.yaml
Inventory File: /home/tpapaioa/.broker/inventory.yaml
Log File: /home/tpapaioa/.broker/logs/broker.log
```
=> Remove deprecated usage of pkg_resources in favor of importlib.metadata.

tests/functional/test_containers.py, tests/functional/test_satlab.py
Functional tests expected `broker_settings.yaml` to be present in the working directory. This PR updates those tests to look in the correct location, using `broker.settings.settings_path` (default: `~/.broker/broker_settings.yaml`).
=> Update functional tests to use correct broker settings location

broker/helpers.py, broker/logger.py
Fixes #223
1. This PR fixes the issue, so that with the following log levels set in `~/.broker/broker_settings.yaml`:
```
logging:
console_level: info
file_level: trace
```
The CLI logs only `info`-level messages to the console, but logs `trace`-level messages to `broker.log`:
```
$ broker execute --workflow list-templates --artifacts last
[INFO 240417 11:02:34] Using provider AnsibleTower for execution
[INFO 240417 11:02:34] Using token authentication
[INFO 240417 11:02:35] No inventory specified, Ansible Tower will use a default.
[INFO 240417 11:02:36] Waiting for job: 
[...]
$ cat ~/.broker/logs/broker.log
[...]
[D 240417 11:02:34 __init__:75] Registered help option inventory for provider inventory
[T 240417 11:02:34 commands:26] Calling func=<function execute at …
```
=> Fix file logging level issue

broker/commands.py, broker/providers/ansible_tower.py, broker/providers/container.py, tests/functional/test_containers.py, tests/functional/test_satlab.py
Extend broker's AnsibleTower and Container provider functionality to pass labels to be set to the spawned resources.
It accepts a string of comma-separated label values.
Broker then uses awxkit session to resolve their id's (required for the job `/launch` payload) and eventually creates the non-existing labels.
User is required to have granted permissions for creating new labels (if that's even a thing) on AAP.
Plan is to implement the labeling functionality to all providers that have support of labels, e.g.
https://docs.docker.com/config/labels-custom-metadata/
example usage:
```
$ broker execute deploy-rhel --provider-labels foo=bar,baz
```
translates to:
(AAP labels are single string items)
```
nick:
rhel8_docker:
container_host: "ubi8:latest"
environment:
BUILD_URL: …
```
=> Add optional provider label support

broker/broker.py, broker/exceptions.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, tests/providers/test_ansible_tower.py
Instead of wrapping everything under a single ProviderError, let's add some nuance.
=> Add more refined exception classes

broker/binds/containers.py, broker/helpers.py, broker/hosts.py, broker/providers/container.py, broker/session.py, broker_settings.yaml.example, tests/data/cli_scenarios/containers/execute_ch-d_ubi8.yaml, tests/functional/README.md, tests/functional/test_containers.py
This change fills the gap previously seen for podman's inability execute commands on containers.
A large part of this was handling the returned output from podman's exec_run, which is a tuple containing the return code and a bytes string containing both the stdout and stderr.
Due to this, we needed to implement a demuxer.
Also made some minor tweaks to the functional tests
=> Add full compatibility for podman

broker/settings.py
There are cases, like github actions, where it is preferable for broker's settings to come from a local repo clone than from github. This change starts with a check for the local clone with a fallback to the source on github.
=> Allow broker_settings example copy from local repo

broker/providers/ansible_tower.py
Try to `POST` to job labels straight away and catch eventual `Duplicate` `400` response.
in such case, retrieve the label id using the `GET` method and carry on.
2 consecutive broker checkout commands with passing the same label should be enough to test this.
the first one creates the label on AAP, while the other one hits the `400` and handles it.
As a result, both resulting AAP jobs have the same job label attached and both broker commands finish successfully.
=> fixes #295 - handle Duplicate error while creating aap job labels

broker/binds/containers.py
This patch ensures that  all kwargs that are being passed to docker-py's container `create` method are sanitized properly and accepted. We missed `RUN_HOST_CONFIG_KWARGS` kwargs keys plus some extra kwargs that have a special handling in docker-py. See the snippet below.
https://github.com/docker/docker-py/blob/a3652028b1ead708bd9191efb286f909ba6c2a49/docker/models/containers.py#L1122-L1157
=> Docker: Handle container create kwargs properly

broker/binds/containers.py, broker/providers/container.py, broker_settings.yaml.example, tests/data/container/fake_networks.json, tests/providers/test_container.py, tests/test_broker.py
We have encountered a couple of issues that need to be solved in order to use Broker with remote podman hosts.
First is an issue with the ssh-based connection to remote podman that was investigated in a previous issue. The
solution to this from Broker's side is largely changing the connection string based on the host_port given.
Second is to give Broker the ability to automatically find and pass along the correct network information when
spinning up an ipv6 container. The solution for this is to list networks, search for one that is ipv6 enabled, then
modify the container creation arguments to pass along that network information
=> Broker changes for remote podman (tcp and ipv6)

broker/binds/containers.py
This time correctly accounting for multiple connection options in the Docker bind, allowing ssh (which is what most people are currently using) to work.
=> Quick fix for docker ssh connection

.github/workflows/codeql-analysis.yml, .github/workflows/python-publish.yml, README.md, pyproject.toml
With recent changes to uv, I am solidifying my position for the use of it over pip.
Part of this includes changing the usage of uv in our actions as well as recomending it in our documentation.
Since most Broker users are no longer also Broker developers, I've changed the quickstart to not involve local development.
=> Updated uv usage and documentation

broker/binds/ssh2.py
This PR fixes a bug in the ssh2 / ssh2-python312 implementation of sftp_read, which was only saving the last chunk of file data locally, in cases where the sftp transfer involves multiple reads.
=> Fix incomplete file downloads in ssh2 sftp_read

broker/commands.py, broker/helpers.py, pyproject.toml
This provides a styled middle ground between the default minimal view and the much more verbose detailed view.
This also give us an opportunity to explore different output styling with rich.
fixes #306
=> Add a curated output flag for inventory

broker/providers/ansible_tower.py
We have quite a lot of users now. This should be a short-term fix.
=> Bump AnsibleTower inventories page limit to 200

broker/helpers.py, pyproject.toml
Podman has changed the return value format for exec commands, when `demux=True`:
https://github.com/containers/podman-py/pull/410
This PR updates `from_duplexed_exec` to handle the new return format.
PRT results: /job/robottelo-pr-testing/8753
=> Fix demux handler

broker/broker.py, broker/providers/__init__.py, tests/test_broker.py
--- First Commit ---
This change simplifies the way we add provider validators to dynaconf. Instead of attempting to add new validators when a class instance is created, we instead add it when the class itself is created. This means that it will happen once immediately when broker is loaded.
--- Second Commit ---
This change rewrites the way broker actions handle concurrency.
Previously, this was offloaded in a manner that was wasteful in the way
it handled pre-action setup.
Now, we don't go concurrent until we're ready to perform the action we
want.
=> Better handling for providers in concurrent actions

broker/binds/hussh.py, pyproject.toml
Previosuly it was impossible to set command-level timeouts when using Hussh as the backend. In fact, due to the way the Host objects acquired their Hussh connections, timeouts were always left to the default. Now, with Hussh 0.1.7, we can pass a command-specific timeout.
Hussh PR for Reference: https://github.com/JacobCallahan/Hussh/pull/14
=> Enable timeouts for command execution when using Hussh

.github/workflows/codeql-analysis.yml, broker/broker.py, broker/commands.py, broker/config_manager.py, broker/config_migrations/v0_6_0.py, broker/helpers.py, broker/hosts.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/session.py, broker/settings.py, broker_settings.yaml.example, pyproject.toml, tests/conftest.py, tests/data/broker_settings.yaml, tests/functional/test_containers.py, tests/test_broker.py, tests/test_config_manager.py
The initial change of this was to introduce the broker config cli. However, to do this, a number of supporting and related changes needed to be made.
The first of these is the new ConfigManager class that manages reading from and writing to the config file.
Since so much logic was implemented for this, it made more sense to roll in the import/init functionality, that was originally in the settings module, into the new class.
This also gave me the opportunity to separate the test config from the example config. This removal, and other changes in this were supported by ConfigManager's migration functionality.
To simplify the nested chunk notation, I moved provider instances out from a list to just being a nested dictionary. This actually simplified the instance logic quite a bit.
Related to …
=> Introduction of broker config cli and much more!

broker/commands.py, broker/config_migrations/v0_6_0.py, broker/helpers.py, broker/settings.py, broker_settings.yaml.example
With the changes we've been making in 0.6 toward a better, more customizable and visually appealing, user experience. It's time that we revisited the inventory command.
The --curated view introduced in 0.5.x has now become the default inventory view. The original default view is now present in its new form and home with the --list flag.
The --details flag largely retains the functionality it did before. However, it involves much less processing than before.
One important piece added in this is the ability to customize the inventory fields on a per-user basis. The details on this customization are documented in detail in the supporting code.
It will also be important to document this in the wiki upon release.
Here's a screenshot of what the new changes look like (with the details view …
=> Rework inventory cli

broker/providers/container.py
In cases, like we currently have, where the container host is podman<5.0 and local podman/podman-py is >=5.0 we run into a TypeError. To solve this, we resort to manually getting the status.
=> Small workaround for container syncing

.github/workflows/codeql-analysis.yml, broker/binds/hussh.py, broker/broker.py, broker/commands.py, broker/config_manager.py, broker/config_migrations/v0_6_0.py, broker/helpers.py, broker/hosts.py, broker/providers/__init__.py, broker/providers/ansible_tower.py, broker/providers/container.py, broker/session.py, broker/settings.py, broker_settings.yaml.example, pyproject.toml, tests/conftest.py, tests/data/broker_settings.yaml, tests/functional/test_containers.py, tests/test_broker.py, tests/test_config_manager.py
This release is primarily focused on UX changes, with some minor fixes/tweaks thrown in.
The three PRs included in these changes are:
#322 
#324 
#325
=> 0.6 Changes

broker/config_manager.py, broker/helpers.py
this change disables certificate validation checks when attempting to download a config file from an https source.
=> Quick fix for https config sources

broker/commands.py, broker/config_manager.py, broker/providers/ansible_tower.py
These include resolving a problem with interactive edits on mac not working. This was likely due to a quirk with the NamedTemporaryFile implementation. I insteda switched to manually creating a temporary file and that worked.
It also includes an early escape for when a user's inventory is empty.
=> More fixes

broker/providers/ansible_tower.py, tests/data/ansible_tower/fake_jobs.json, tests/providers/test_ansible_tower.py
This PR:
- removes the old method of pulling host data from AAP, which is no longer used since https://github.com/SatelliteQE/broker/pull/261
- updates the test data for the mock workflow job, to reflect the newer method
=> Remove deprecated method for pulling AnsibleTower host facts

broker/providers/ansible_tower.py
Until this change, if a user gave an incorrect name, Broker would give a traceback that wasn't helpful. Now, when the items can't be found, it will give back a more helpful message.
=> Add checks for bad input for AT provider help paths

broker/providers/container.py
When a user syncs a Container provider with at least one container that is missing from their local inventory, it breaks their local executions of `broker inventory`.
With this change, we reconstruct the "_broker_args" with what limited information is available from the synced container instance.
=> Improve container provider syncs

broker/providers/ansible_tower.py
Cole encountered an issue where inventory syncs were failing because ruamel wasn't able to handle awxkit's Psuedonamespace objects. This simply adds a new representer for them, fixing the issue.
=> Fix for ruamel interactions with awxkit objects

broker/hosts.py
As identified in #334, we can get into a state during garbage collection where a Host instance's _session attribute is missing. However, the del method calls close, which expects that attribute to be in place.
In this change, we add a couple of conditions to the del to gate the close call.
fixes #334
=> Fix issue around host garbage collection

broker/providers/ansible_tower.py
We've been seeing some issues with service interruptions in AAP under high load. While the jobs do complete successfully, awxkit bails when encountering the connection issue.
With this change, we simple enter a retry loop when monitoring job status.
=> Make AnsibleTower checkout/execute actions more resilient

broker/commands.py
Sometimes a user may pass incorrect host information to a checkin. In those events, they won't receive feedback about the incorrect input. This change collects hosts that aren't matched and reports them back to the user in a warning message.
```
❯ broker checkin something another and more
[WARNING 250121 13:47:07] The following hosts were not found in inventory: something, and, more, another
```
=> Add a warning message if a user tries to checkin incorrect hosts

pyproject.toml
Now that ssh2-python has returned, let's switch the primary ssh-backend dependency to it. This primary dependency will be removed in Broker 0.7 along with the ssh2_python311 and ssh2_python312 optional dep definitions.
Also, with the merge of #346, we can fix how the license is attributed in the project metadata. This moves us in compliance with the newer PEP 639 standard.
Fixes #347
=> pyproject.toml updates

.github/workflows/codeql-analysis.yml, pyproject.toml
Now that we aren't held back by a newer version of ssh2-python312, we should be able to bump the project up to python 3.13.
=> Bump tp Python 3.13

broker/hosts.py
**Problem Statement :** 
The connect method does not work with IPv6 addresses. It returns an error
**Solution :** 
Update host connect method to handle IPv6 address
=> Update host connect method to handle IPv6 address

broker/providers/container.py
Previously, if a user set a hostname on a container, Broker wouldn't recognize that. This is because we just looked up the container's id. When a hostname isn't set at runtime, this is perfectly fine. However, when a user does set a hostname, this breaks what would be expected.
With this change, we have a more reliable way to solve both cases.
=> Update the way we're getting a container's hostname

broker/helpers.py, tests/functional/test_containers.py
Looks like a recent change has allowed these values to potentially be None. In this case, we shouldn't try to decode and just return an empty string.
Also included a functional test that didn't make it into the previous commit adding the hostname change.
=> Handle decodes when stdout or stderr is None

broker/broker.py
In some cases, the `hostname` attribute is not set or available on AAP hosts. For example:
```
Id | Hostname              | Name
0  | Unknown               | tpapaioa-AAP-MR1
1  | Unknown               | tpapaioa-AAP-MR2
2  | host1.example.com     | tpapaioa-rhel-9.5-3
```
If I check in one of these hosts, then broker removes all of them from `inventory.yaml`, instead of just the one that was removed from AAP:
```
$ broker checkin 0
[....]
$ broker inventory
Id | Hostname              | Name
0  | host1.example.com     | tpapaioa-rhel-9.5-3
```
This PR updates `Broker.checkin()` to pass the host's unique `name` attribute instead, so that only the given hosts are removed from the inventory.
=> Remove hosts from local inventory by (unique) name instead of hostname during checkin

broker/hosts.py
If a user sets a default timeout on the host class, but wants to pass a timeout of 0 to a command, it will currently use the default since the check relies on "falsey" values.
In this change, we're just going to be more specific with the conditional check.
=> Update timeout logic to better handle "falsey" values

broker/providers/ansible_tower.py
During a `broker checkout` against an AnsibleTower (AAP) provider, any cached facts that are stored on the host in AAP under the `_broker_facts` key will be added to the host record in broker's local inventory.yaml. For example,
AAP Host Facts:
```
_broker_facts:
shutdown_time: 'X'
```
Broker inventory:
```
- name: my_vm
shutdown_time: 'X'
```
These fields aren't added or updated by `broker inventory --sync AnsibleTower`, however, so any changes to the host's facts after its initial checkout will never show up in broker's inventory.
This PR updates the inventory sync to update these fields in inventory.yaml during inventory sync.
```
$ broker checkout --workflow deploy-rhel
$ broker inventory --details | grep _time
$ broker extend 0
$ broker inventory --sync AnsibleTower
$ broker …
```
=> Get _broker_facts in AnsibleTower inventory sync

broker/commands.py
With this change, `broker checkout --help `  will show that `--AnsibleTower <instance> ` is a valid option to be used.
=> Add help entry describing how to chose specific AnsibleTower instance

broker/binds/hussh.py
Hussh isn't a fan of multiple types here, so we'll explicitly convert them to strings so users don't have to.
=> Explicitly convert python paths into strings for Hussh

broker/config_migrations/v0_6_9.py, broker/helpers.py, broker/providers/ansible_tower.py, broker_settings.yaml.example
This change makes it possible for users to interact with AAP 2.5+ without having to set the awxkit environment variable themselves.
This path currently is a bit heavy-handed, but may be simplified in the future.
=> Changes needed for AAP 2.5 compatibility

broker/providers/ansible_tower.py
This PR fixes #372 - an issue with serialization of Enum values in kwargs passed to awxkit (AWX/AAP).
Currently, when passing Enum objects (like NetworkType) in kwargs to AWX's execute method, the code uses `str(kwargs)` which produces a string representation that includes Python object references rather than their actual values. This causes improper serialization and interpretation on the AWX side.
Replace `str(kwargs)` with `json.dumps(kwargs)` to properly serialize the kwargs dictionary, ensuring Enum values are converted to their string representations and the entire structure is converted to valid JSON.
- Ensures consistent serialization of all objects passed to AWX/AAP
- Prevents cryptic errors when using structured data in workflows
- More maintainable and standard approach to API …
=> Proper payload serialization for awxkit

broker/binds/containers.py
Remove the finally block and reinsert the mounts before return, so bind mounts aren’t dropped.
=> Preserve mounts in PodmanBind sanitizer
