- broker/helpers.py
Documentation for helper functions in broker
> Documentation for helper.py

- HISTORY.rst
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/providers/ansible_tower.py
- broker/providers/test_provider.py
- setup.py
Changed the location of the logic for checkin and checkout
Consolidated most of the logic under the VMBroker class to allow
it to be more useful for non-cli users.
Added a TestProvider class in preparation for upcoming tests.
> Minor project refactor

- .travis.yml
- HISTORY.rst
- broker/broker.py
- broker/helpers.py
- broker/hosts.py
- broker/providers/ansible_tower.py
- broker/providers/test_provider.py
- settings.yaml.example
- setup.py
- tests/data/ansible_tower/fake_children.json
- tests/data/ansible_tower/fake_jobs.json
- tests/providers/test_ansible_tower.py
- tests/test_broker.py
+ Added initial tests
+ Added travis integration
+ Added a helper method for tests
+ Minor fixes and tweaks
> Add initial tests to broker

- .gitignore
- broker/commands.py
- broker/logger.py
Small change to the log level setting pattern.
Needs testing, pushing to get early feedback on the approach.
> Update log level setting pattern

- broker/commands.py
- broker/providers/ansible_tower.py
Documentation for commands.py and ansible_tower.py files.
> Finish documentation

- HISTORY.rst
- README.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/providers/__init__.py
- broker/providers/ansible_tower.py
- setup.py
This change adds in a new subcommand that will help users define their own nicks
Also added is a new helper function that assists in printing/logging
yaml-formatted data structures
Finally, I used that helper in better presenting inventory details
> Add nick-help subcommand

- HISTORY.rst
- README.md
- broker/broker.py
- broker/commands.py
- broker/hosts.py
- broker/providers/ansible_tower.py
- broker/session.py
- settings.yaml.example
- setup.py
Host objects can now establish an ssh connection to their corresponding host.
+ Added session class
+ Added session functionality to Host class
+ Updated VMBroker context manager
+ Added ssh2-python dependency (requires cmake)
+ New host settings added to settings.yaml.example
> Add session functionality to Host objects

- HISTORY.rst
- broker/broker.py
- broker/commands.py
- broker/providers/ansible_tower.py
- setup.py
+ Added execute functionality to broker
+ Added more functionality to VMBroker subclass to handle execute
+ Slightly changed AnsibleTower provider to allow for arbitrary workflow execution
> Add execute subcommand to broker

- Dockerfile
- broker/providers/ansible_tower.py
Added ability to build broker in a container
You should mount the broker directory to /root/broker in the container
> Add Dockerfile

- HISTORY.rst
- README.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/providers/__init__.py
- broker/providers/ansible_tower.py
- setup.py
+ Added the ability to query actions from providers using nick-help
+ Misc enhancements and tweaks including improving inventory host removal
> Added inventory sync functionality to broker

- README.md
- broker/broker.py
- broker/providers/ansible_tower.py
This change allows broker to pull available workflow information during
a sync with an AnsibleTower inventory
Minor typo fixes and an alternate code format change
> Minor fixes and tweaks

- broker/broker.py
This allows broker to truly checkin all hosts at once
> Fix broker skipping every other host during checkin --all

- HISTORY.rst
- README.md
- broker/broker.py
- broker/commands.py
- broker/providers/__init__.py
- broker/providers/ansible_tower.py
- broker_settings.yaml.example
- setup.py
Changed --artifacts to now accept merge or last
Misc small changes
**Note:** This adds a new field in the ansible tower settings for `extend_workflow`
> Added ability to extend vm lease time

- broker/providers/ansible_tower.py
This will help to reduce load on the AT api
> Only pull last child node when artifacts strategy is last

- HISTORY.rst
- README.md
- broker/broker.py
- broker/commands.py
- setup.py
- tests/test_broker.py
VMBroker now has the ability to multiprocess checkouts
The decorator is likely general to other VMBroker methods, but hasn't
been applied at this point.
Also, Broker is now v0.1.0
> Introducing multiprocessing for broker checkouts

- HISTORY.rst
- README.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- setup.py
Filters are now available to decide which hosts are selected for certain actions.
VMBroker can now reconstruct hosts from the local inventory
> Introducing filters and host reconstruction

- .travis.yml
- HISTORY.md
- README.md
- setup.py
This should allow pip installation from pypi
fixes #56
> Moved HISTORY.rst to HISTORY.md

- .github/workflows/codeql-analysis.yml
Setup Github security scanning
With the merge of this PR, github will now scan future pull requests for potential security issues.
> Add automated security scanning

- HISTORY.md
- broker/providers/ansible_tower.py
- setup.py
This accounts for when tower doesn't provide a child node result
> Minor fix for AnsibleTower provider

- LICENSE
This is the same license we include with robottelo
Fixes #67
> Add GNU license

- .gitignore
- HISTORY.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/providers/ansible_tower.py
- broker/settings.py
- broker_settings.yaml.example
- setup.py
list-templates becomes a first-class component of AnsibleTower
new setting added to limit the amount of templates shown. default: 20
> Added a list-templates ability for AnsibleTower provider

- .travis.yml
- broker/providers/test_provider.py
- pytest.ini
- setup.py
This is to work arround issue with TestProvider class attempts to be collected
as test class.
> Don't run pytest on other dir than tests

- .travis.yml
- broker/providers/ansible_tower.py
Changing strategy="merge" to strategy="last"
> small PR for merge_artifact

- HISTORY.md
- README.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/hosts.py
- broker/logger.py
- broker/providers/__init__.py
- broker/providers/ansible_tower.py
- broker/providers/test_provider.py
- broker/settings.py
- broker_settings.yaml.example
- setup.py
- tests/test_settings.py
+ Added the concept of instances
+ Broker now passes along a host's stored _broker_args during checkin
fixes #81
> Refactored broker's settings and dynaconf validator patterns

- broker/broker.py
> Fix traceback when checking out multiple VMs with connect=True

- broker_settings.yaml.example
Hello
Remove redundant `provider` setting and bump the example nick rhel7 version.
> Remove provider key and bump rhel version

- HISTORY.md
- broker/broker.py
- broker/providers/ansible_tower.py
- setup.py
Also, add tower_inventory field when gathering host info
> Allow VMBroker to checkin hosts not in its inventory

- HISTORY.md
- broker/broker.py
- broker/exceptions.py
- broker/hosts.py
- broker/session.py
- setup.py
It is now possible to define setup and teardown behavior
HostErrors now how their own exception class
> Added some enhancements to the default Host class

- HISTORY.md
- broker/broker.py
- broker/commands.py
- broker/providers/ansible_tower.py
- broker_settings.yaml.example
- setup.py
Also, minor fix to VMBroker context manager
> AnsibleTower users can now specify a new expire vm time

- HISTORY.md
- broker/broker.py
- broker/providers/ansible_tower.py
- broker/session.py
- setup.py
This enables direct file copying from one broker host object to another!
> Added remote_copy to the Host's session object

- HISTORY.md
- README.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/hosts.py
- broker/providers/ansible_tower.py
- broker/session.py
- setup.py
- tests/test_helpers.py
Added Emitter class and emit instance to helpers
Added a way to gain failure information for AnsibleTower
> Added the ability to store important output from cli

- HISTORY.md
- broker/broker.py
- broker/hosts.py
- broker/providers/ansible_tower.py
- setup.py
Also increased AnsibleTower page size for workflows and job templates.
Using the _prov_inst also made it so we only auth once per CLI host checkin!
A little bit of black formatting happened as well..
This is an alternative PR to #117
> Improved concurrent checkin resilience

- HISTORY.md
- broker/hosts.py
- broker/session.py
This change adds a method to the session object which allows it to spawn
an interactive shell in a new channel.
Also made some small tweaks to fix an issue with closing sessions.
> Add interactive shell

- HISTORY.md
- broker/broker.py
- broker/commands.py
- broker/helpers.py
- broker/logger.py
- broker/session.py
+ Extends are now concurrent by default
+ Color codes are stripped from log files
+ Broker now respects its own debug setting
+ Session command timeouts are now flexible
Fixes #133
Fixes #135
> Fixing things up in preparation for larger changes

- HISTORY.md
- broker/helpers.py
- broker/session.py
Also added some better error handling when decoding stdout data
> Added retries to socket.connect

- HISTORY.md
- broker/commands.py
- broker/hosts.py
- broker/logger.py
- broker/providers/ansible_tower.py
- tests/providers/test_ansible_tower.py
Also, silenced urllib3 warnings for users who make questionable decisions
> Added basic support for AAP

- broker/hosts.py
- broker/session.py
- broker/settings.py
- broker_settings.yaml.example
Realize the non-default port 22 guest connect on broker.
Cases PASS for default port 22 connect and non-default guest connect by command.
> Realize non-default port guest connect on broker

- broker/hosts.py
We've observed behavior where Host._purify would endlessly recurse in
some situations. This has necessitated a better way of handling those
cases.
The new implementation moves the RecursionError check outside
Host._purify and into Host.__getstate__ where it should be caught.
From there, we remove the offending object and continue.
> Add better handling for recursive purify situations

- broker/broker.py
In the event that some exception happens during checkout in Broker's contextmanger, try to call that host's teardown
> Add teardown to unsuccessful contextmanager checkouts

- broker/hosts.py
- broker/session.py
- broker/settings.py
- broker_settings.yaml.example
This PR adds support for key-based authentication to the `broker.hosts.Host`s.
> Add full support for key-based authentication

- broker/broker.py
- broker/helpers.py
- broker/providers/ansible_tower.py
- broker/providers/container.py
- broker/session.py
Switch ProcessPoolExecutor to ThreadPoolExecutor since these tasks are IO bound. Additionally, experiment with class and session caching.
> Add optimizations for concurrency

- broker/session.py
- tests/functional/test_containers.py
- tests/functional/test_satlab.py
This PR allows the user to get the `bytes` object without writing the data to the system.
I have used `sftp_read` method instead of creating a new one.
To be used in SatelliteQE/robottelo#10547
> Let sftp_read return data

- catalog-info.yaml
We're testing backstage and would like to add Broker to the catalog.
> Adding basic catalog for Backstage integration

- broker_settings.yaml.example
This is needed for an upcoming change.
> Add Beaker to broker_settings.yaml.example

- broker/commands.py
> Don't show index if using a filter on inventory

- .github/workflows/python-publish.yml
- pyproject.toml
This will allow us to install the dependencies for building the project in one location for users and the action.
> Add setup dependency group to pyproject.toml

- .github/workflows/codeql-analysis.yml
- broker/providers/ansible_tower.py
- pyproject.toml
Adding python 3.12 to github checks and pyproject.toml
> Add support for python 3.12

- .github/workflows/codeql-analysis.yml
- .github/workflows/python-publish.yml
- Dockerfile
uv now let's us install to system python instead of requiring a virtual environment.
> Simplify uv use

- broker/providers/ansible_tower.py
- tests/functional/test_satlab.py
This change addresses some minor issues we've seen with a new exception. Additionally, it simplifies the AnsibleTower instance repr in logging.
> Minor changes to logging and exceptions

- broker/binds/foreman.py
- tests/providers/test_foreman.py
* Remove invalid provider argument
* Handle additional error message format
* Write tests for interpret_response
* Make kwargs usable
> Fix minor bugs in foreman bind

- broker/hosts.py
Add deploy_network_type for hosts.
> Add deploy_network_type

- broker/broker.py
- broker/commands.py
This change is primarily based around propagating errors in a more correct way. Previously, we stripped them out during host construction, which was masked due to the errors still being logged on init.
Now, we keep the errors how they should be and raise the latest. This also combines a the loggedcli with the ExceptionHandler class in the cli to reduce redundancy.
Finally, we're not going to re-log the exception message as the command exits.
> Allow checkout errors to propagate correctly

- broker/providers/ansible_tower.py
In AAP 2.5, token-based authentication results in significantly less errors. Because of this, we are going to attempt to create a temporary token, when a user only gives us their username and password.
> Create temporary tokens when AnsibleTower users provide basic auth
